import { beforeEach, describe, test } from "vitest";
import { expect } from "chai";
import { Board } from "../src/Board";

describe("Board can be created from a string", () => {
  test("Created from a string", () => {
    const board = new Board(6, 6);
    board.setBoard(
      `......
            ......
            ......
            ......
            TTT...
            .T....`
    );
    expect(board.toString()).to.equalShape(`
                ......
            ......
            ......
            ......
            TTT...
            .T....
                `);
  });
});
