import { beforeEach, describe, test } from "vitest";
import { expect } from "chai";
import { Board } from "../src/Board";
import { Tetromino } from "../src/Tetromino";

describe("Board can be created from a string", () => {
  let board;
  beforeEach(() => {
    board = new Board(6, 6);
  });
  test("Set board from a string works", () => {
    board.setBoard(
      `......
            ......
            ......
            ......
            TTT...
            .T....`
    );
    expect(board.toString()).to.equalShape(`
                ......
            ......
            ......
            ......
            TTT...
            .T....
                `);
  });
  test("Falling tetromino get's removed if on board before creation", () => {
    board.drop(Tetromino.T_SHAPE2);
    board.setBoard(
      `......
              ......
              ......
              ......
              TTT...
              .T....`
    );
    board.tick();
    expect(board.toString()).to.equalShape(`
                  ......
              ......
              ......
              ......
              TTT...
              .T....
                  `);
  });
});
